### PR TITLE
feat: esm support

### PR DESCRIPTION
**Pull request by dangreen**
Need to solve https://github.com/chartjs/Chart.js/pull/10917

### CODE REVIEW

**Comment by dangreen** [comment]
@kurkle review pls 🙏

**Review by kurkle — DISMISSED** [review]
Looks good, thanks!

**Comment by kurkle** [comment]
Except some dependency issues, at least typedoc needs to be updated.

**Comment by dangreen** [comment]
@kurkle done

**Review by kurkle — APPROVED** [review]

**Pull request merged**
