### PR TITLE
fix: commonjs bundle compat with esm

### PR DESCRIPTION
**Pull request by dangreen**
Fixes https://github.com/chartjs/Chart.js/issues/11036

### CODE REVIEW

**Comment by dangreen** [comment]
@kurkle please review 🙏

**Review by kurkle — COMMENTED** [review]
How is the output different compared to using index.esm as entry for the umd build?

What issue is this solving?

**Comment by dangreen** [comment]
@kurkle ESM bundle provides named exports, the CommonJS bundle - does not. In this PR, I added named exports to the CommonJS Bundle.

**Comment by kurkle** [comment]
And is the default export compatible too? To me it looks like this new one will be just a recursive object?

**Comment by dangreen** [comment]
@kurkle yes

```
> const color = require('.')
undefined
> color
<ref *1> [Function: index_esm] {
  Color: [class Color],
  default: [Circular *1],
  round: [Function: round],
  lim: [Function: lim],
  p2b: [Function: p2b],
  b2p: [Function: b2p],
  n2b: [Function: n2b],
  b2n: [Function: b2n],
  n2p: [Function: n2p],
  hexParse: [Function: hexParse],
  hexString: [Function: hexString],
  rgb2hsl: [Function: rgb2hsl],
  hsl2rgb: [Function: hsl2rgb],
  hwb2rgb: [Function: hwb2rgb],
  hsv2rgb: [Function: hsv2rgb],
  hueParse: [Function: hueParse],
  rotate: [Function: rotate],
  hslString: [Function: hslString],
  nameParse: [Function: nameParse],
  rgbParse: [Function: rgbParse],
  rgbString: [Function: rgbString]
}
> color('white')
Color { _rgb: { r: 255, g: 255, b: 255, a: 255 }, _valid: true }
> new color.Color('white')
Color { _rgb: { r: 255, g: 255, b: 255, a: 255 }, _valid: true }
> 
```

"default" export is a function with assigned properites

**Review by kurkle — APPROVED** [review]

**Pull request merged**
